# Generated by Django 4.1.4 on 2023-01-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.DeleteModel(
            name='LabelForTask',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='labels.label'),
        ),
    ]
